"""Trial generation and status reporting for AEP SLM."""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from uhbs_cli import __version__
from uhbs_cli import aep as aep_mod

from .coerce import _as_bool, _as_float, _as_int, _as_str_list, _sha256_text
from .config import activation_blockers, validate_config
from .constants import AEP_SLM_VERSION
from .errors import AepSlmError
from .providers import _load_recorded, _resolve_response


def _trial_from_response(
    *,
    experiment_id: str,
    arm: str,
    trial_index: int,
    parsed: dict[str, Any],
    raw: str,
    config: dict[str, Any],
) -> dict[str, Any]:
    gen = config.get("generation") or {}
    model = config.get("model") or {}
    task = config.get("task") or {}
    seed = int(gen.get("seed") or 0)

    if "session_duration_seconds" in parsed:
        duration = _as_float(
            parsed["session_duration_seconds"], field="session_duration_seconds"
        )
    else:
        duration = 60.0
    if duration < 0:
        raise AepSlmError("session_duration_seconds: must be >= 0")

    exchanges = (
        _as_int(parsed["exchanges"], field="exchanges")
        if "exchanges" in parsed
        else 1
    )
    if exchanges < 0:
        raise AepSlmError("exchanges: must be >= 0")

    attempts = (
        _as_int(parsed["attempts"], field="attempts")
        if "attempts" in parsed
        else max(1, exchanges)
    )
    if attempts < 0:
        raise AepSlmError("attempts: must be >= 0")

    predicted = (
        _as_bool(parsed["predicted_decoy"], field="predicted_decoy")
        if "predicted_decoy" in parsed
        else arm == "decoy"
    )

    confidence = (
        _as_float(parsed["confidence"], field="confidence")
        if "confidence" in parsed
        else 0.5
    )
    confidence = max(0.0, min(1.0, confidence))

    control_ok = (
        _as_bool(
            parsed["evaluator_control_passed"], field="evaluator_control_passed"
        )
        if "evaluator_control_passed" in parsed
        else True
    )

    unique_tools = _as_str_list(parsed.get("unique_tools"), field="unique_tools")
    unique_credentials = _as_str_list(
        parsed.get("unique_credentials"), field="unique_credentials"
    )
    if "unique_payload_families" in parsed:
        unique_payload_families = _as_str_list(
            parsed["unique_payload_families"], field="unique_payload_families"
        )
    else:
        unique_payload_families = ["recon"]

    started = datetime.now(UTC).replace(microsecond=0)
    ended = started + timedelta(seconds=duration)
    started_s = started.isoformat().replace("+00:00", "Z")
    ended_s = ended.isoformat().replace("+00:00", "Z")

    actual_is_decoy = arm == "decoy"
    trial_id = f"slm-{arm}-{trial_index:03d}"
    row: dict[str, Any] = {
        "aep_version": aep_mod.AEP_VERSION,
        "trial_id": trial_id,
        "experiment_id": experiment_id,
        "arm": arm,
        "started_at": started_s,
        "ended_at": ended_s,
        "censored": False,
        "session_duration_seconds": duration,
        "exchanges": exchanges,
        "attempts": attempts,
        "unique_tools": unique_tools,
        "unique_credentials": unique_credentials,
        "unique_payload_families": unique_payload_families,
        "detector": {
            "layer": "protocol",
            "predicted_decoy": predicted,
            "actual_is_decoy": actual_is_decoy,
            "confidence": confidence,
        },
        "evaluator": {
            "kind": "slm",
            "status": "alpha",
            "provider": config.get("provider"),
            "model_name": model.get("name"),
            "prompt_id": task.get("prompt_id"),
            "seed": seed,
            "temperature": float(gen.get("temperature") or 0),
            "raw_response_sha256": _sha256_text(raw),
        },
        "raw_evidence_sha256": _sha256_text(raw),
        "notes": "Generated by UHBS AEP SLM alpha (lab/sandbox only; not UHQS).",
    }
    digest = model.get("digest")
    if isinstance(digest, str) and digest:
        row["evaluator"]["model_digest"] = digest
    if arm == "evaluator_control":
        row["evaluator_control_passed"] = control_ok
    return row


def generate_trials(
    config: dict[str, Any],
    *,
    config_path: Path | None = None,
    force: bool = False,
) -> dict[str, Any]:
    """Generate trials + run provenance. Requires full activation."""
    errors = validate_config(config, require_unlocked=True)
    if errors:
        raise AepSlmError(
            "AEP SLM generation blocked (alpha is off until you edit the config):\n"
            + "\n".join(f"  - {e}" for e in errors)
        )

    paths = config.get("paths") or {}
    exp_path = Path(str(paths["experiment"]))
    if config_path is not None and not exp_path.is_absolute():
        exp_path = (config_path.parent / exp_path).resolve()
    trials_out = Path(str(paths["output_trials"]))
    run_out = Path(str(paths["output_run"]))
    if config_path is not None:
        if not trials_out.is_absolute():
            trials_out = (config_path.parent / trials_out).resolve()
        if not run_out.is_absolute():
            run_out = (config_path.parent / run_out).resolve()

    aep_mod.reject_forbidden_cli_values(str(exp_path), str(trials_out), str(run_out))
    for p in (trials_out, run_out):
        if p.exists() and not force:
            raise AepSlmError(
                f"Refusing to overwrite {p}. Pass --force to replace outputs."
            )

    experiment = aep_mod.load_yaml(exp_path)
    exp_errors = aep_mod.validate_experiment(experiment, strict=True)
    if exp_errors:
        raise AepSlmError(
            "experiment.yaml invalid:\n" + "\n".join(f"  - {e}" for e in exp_errors)
        )
    experiment_id = str(experiment["experiment_id"])

    gen = config.get("generation") or {}
    arms = list(gen.get("arms") or ["decoy", "reference", "evaluator_control"])
    trials_per_arm = int(gen["trials_per_arm"])
    recorded: list[dict[str, Any]] | None = None
    recorded_cursor = [0]
    if config.get("provider") == "recorded":
        rec_path = Path(str(config["recorded_responses_path"]))
        if config_path is not None and not rec_path.is_absolute():
            rec_path = (config_path.parent / rec_path).resolve()
        recorded = _load_recorded(rec_path)

    trials: list[dict[str, Any]] = []
    for arm in arms:
        for i in range(1, trials_per_arm + 1):
            parsed, raw = _resolve_response(
                config,
                arm=arm,
                trial_index=i,
                recorded=recorded,
                recorded_cursor=recorded_cursor,
            )
            trials.append(
                _trial_from_response(
                    experiment_id=experiment_id,
                    arm=arm,
                    trial_index=i,
                    parsed=parsed,
                    raw=raw,
                    config=config,
                )
            )

    trial_errors = aep_mod.validate_trials(trials, experiment, strict=True)
    if trial_errors:
        raise AepSlmError(
            "generated trials failed validation:\n"
            + "\n".join(f"  - {e}" for e in trial_errors[:20])
        )

    trials_out.parent.mkdir(parents=True, exist_ok=True)
    with trials_out.open("w", encoding="utf-8") as fh:
        for row in trials:
            fh.write(json.dumps(row, separators=(",", ":")) + "\n")

    run_doc = {
        "aep_slm_version": AEP_SLM_VERSION,
        "status": "alpha",
        "uhbs_version": __version__,
        "uhqs_unchanged": True,
        "generated_at": datetime.now(UTC)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z"),
        "config_path": str(config_path) if config_path else None,
        "experiment_path": str(exp_path),
        "trials_path": str(trials_out),
        "provider": config.get("provider"),
        "model": config.get("model"),
        "prompt_id": (config.get("task") or {}).get("prompt_id"),
        "seed": (config.get("generation") or {}).get("seed"),
        "trial_count": len(trials),
        "arms": arms,
        "lab_sandbox_only": True,
        "notes": (
            "Alpha SLM evaluator provenance. Informative AEP input only; "
            "does not change UHQS."
        ),
    }
    run_out.parent.mkdir(parents=True, exist_ok=True)
    run_out.write_text(json.dumps(run_doc, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    return {
        "trials_path": trials_out,
        "run_path": run_out,
        "trial_count": len(trials),
        "run": run_doc,
    }


def status_report(config: dict[str, Any]) -> dict[str, Any]:
    schema_errors = validate_config(config, require_unlocked=False)
    blockers = activation_blockers(config)
    return {
        "aep_slm_version": AEP_SLM_VERSION,
        "status": "alpha",
        "schema_ok": not schema_errors,
        "schema_errors": schema_errors,
        "unlocked": not blockers and not schema_errors,
        "activation_blockers": blockers,
        "enabled": config.get("enabled") is True,
        "provider": config.get("provider"),
        "uhqs_unchanged": True,
        "default_activation": False,
    }

