[deception]
  server_name = "nginx"

[http]
  bind_addr = "0.0.0.0"
  bind_port = "8080"
  real_ip_header = 'X-Real-IP'
  uagent_string_blacklist = ["Cloudflare-Traffic-Manager"]

  [http.router]
    catchall = true
    makerobots = false

[logger]
  debug = false
  trace = false
  directory = "/telemetry/"
  nocolor = true
  use_date_filename = true
